CREATE CONSTRAINT drink_id_unique IF NOT EXISTS
FOR (d:Drink) REQUIRE d.id IS UNIQUE;

CREATE CONSTRAINT flavor_name_unique IF NOT EXISTS
FOR (f:Flavor) REQUIRE f.name IS UNIQUE;

CREATE CONSTRAINT user_id_unique IF NOT EXISTS
FOR (u:User) REQUIRE u.id IS UNIQUE;
