services:
  neo4j:
    image: 'neo4j:latest'
    container_name: neo4j
    ports:
        - "7474:7474"   # Neo4j Browser (interfaz web)
        - "7687:7687"   # Bolt (lo que usa el driver de Java)
    environment:
        - NEO4J_AUTH=neo4j/tu_password
    volumes:
        - ./import:/var/lib/neo4j/import
        - ./data:/data

